version: '3.3'

services:
  web-server:
    image: nginx:1.21.6-alpine
    container_name: web-server
    restart: always
    volumes:
      - /etc/letsencrypt/live/${DOMAIN_NAME}/fullchain.pem:/etc/ssl/${DOMAIN_NAME}/cert.crt
      - /etc/letsencrypt/live/${DOMAIN_NAME}/privkey.pem:/etc/ssl/${DOMAIN_NAME}/privkey.key
      - ./nginx.conf:/etc/nginx/templates/default.conf.template
    command: [nginx, '-g', 'daemon off;']
    environment:
          DOMAIN_NAME: ${DOMAIN_NAME}
    depends_on:
      - webpage
    ports:
      - 80:80
      - 443:443

  ${WEBPAGE_NAME}:
    build: .
    image: ${WEBPAGE_NAME}
    container_name: ${WEBPAGE_NAME}
    restart: always
    environment:
      NODE_ENV: production 