version: '3.3'

services:
  ${WEBPAGE_NAME}-dev:
    build: 
        context: .
        dockerfile: Dockerfile.dev
    image: ${WEBPAGE_NAME}-dev
    container_name: ${WEBPAGE_NAME}-dev
    volumes:
      - ./src:/app/src
      - ./views:/app/views
      - ./assets:/app/assets
      - /app/node_modules
    restart: always
    environment:
      NODE_ENV: development
    ports: 
      - 8100:8080   