apiVersion: v1
kind: Service
metadata:
  name: ${MICROSERVICE_NAME}-service
spec:
  type: NodePort
  selector:
    app: ${MICROSERVICE_NAME}-microservice
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
