version: "3"

services:
    ${MICROSERVICE_NAME}:
        build: 
            context: .
            dockerfile: Dockerfile.dev
        image: ${MICROSERVICE_NAME}
        container_name: ${MICROSERVICE_NAME}
        environment: 
            NODE_ENV: development
            TITLE: ${MICROSERVICE_NAME}
            ALLOWED_ORIGINS: '["capacitor://localhost","ionic://localhost","http://localhost","http://localhost:8080","http://localhost:8100"]'
            PORT: 8080
        volumes:
            - ./src:/app/src
            - ./models:/app/models
            - ./.insomnia:/app/.insomnia
            - app-node_modules:/app/node_modules
            - ./data:/app/data
        restart: 'always'
        ports:
            - 8080:8080
            - 9229:9229

volumes: 
    app-node_modules: