FROM node:17-alpine 

WORKDIR /app

ENV PATH /app/node_modules/.bin:$PATH

COPY ./package.json /app/package.json

COPY ./package-lock.json /app/package-lock.json

RUN npm install

COPY ./ /app

CMD sh -c  "npm run watch:debug"
