version: "3"

services:
    ${MICROSERVICE_NAME}:
        build: .
        image: ${MICROSERVICE_NAME}
        container_name: ${MICROSERVICE_NAME}
        environment: 
            NODE_ENV: development
            TITLE: ${MICROSERVICE_NAME}
            API_VERSION: '1.0'
            SERVICE_BASE_URL: '/'
            ALLOWED_ORIGINS: '["capacitor://localhost","ionic://localhost","http://localhost","http://localhost:8080","http://localhost:8100"]'
            PORT: 8080
        volumes:
            - ./src:/app/src
            - ./models:/app/models
            - ./swagger.yml:/app.swagger.yml
            - app-node_modules:/app/node_modules
            - ./data:/app/data
        restart: 'always'

volumes: 
    app-node_modules: